version: "2"
linters:
  enable:
    - bodyclose
    - revive
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: error return value not checked.*Close
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
